arch: "RINEModel"
name: "rine_incremental"

model:
  backbone0: "ViT-L/14"
  backbone1: 1024
  nproj: 2
  proj_dim: 1024

train:
  pipeline: engine.base_trainer
  factor: 0.2
  gpu_ids: [0]
  train_epochs: 1 
  check_val_every_n_epoch: 1 
  seed: 1995
  optimizer:
    _target_: torch.optim.Adam
    _partial_: True
    lr: 1e-3
    weight_decay: 1e-3
    betas: [0.9, 0.999]

  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: True
    T_max: ${train.train_epochs} 

datasets:
  base_path: "/data/yabin/DF-arrow-data" 
  train:
    source:
      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/ForenSynths',
          sub_sets: [ "car" ],
          split: 'train_binary' }
      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/ForenSynths',
          sub_sets: [ "chair" ],
          split: 'train_binary' }      
      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/ForenSynths',
          sub_sets: [ "horse"],
          split: 'train_binary' }
      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/ForenSynths',
          sub_sets: [ "cat" ],
          split: 'train_binary' }
    split_ratio: 0.9
    batch_size: 128
    loader_workers: 32
    trsf:
      - _target_: data.DataAugment
        blur_prob: 0.5
        blur_sig: [ 0.0, 3.0 ]
        jpg_prob: 0.5
        jpg_method: [ 'cv2', 'pil' ]
        jpg_qual: [ 30, 100 ]
      - _target_: torchvision.transforms.RandomCrop
        size: 224
      - _target_: torchvision.transforms.RandomHorizontalFlip
        p: 0.5
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [ 0.48145466, 0.4578275, 0.40821073 ]
        std: [ 0.26862954, 0.26130258, 0.27577711 ]

  test:
    source:
      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/DIF',
          sub_sets: [ 'dalle_2', ],
          split: 'test',
          benchmark_name: 'DIF' }

      - { target: data.ArrowDatasets,
        data_root: '${datasets.base_path}/GANGen-Detection',
        sub_sets: [ "AttGAN", ],
        split: 'test',
        benchmark_name: 'GANGen-Detection' }

    batch_size: 128
    loader_workers: 32
    trsf:
      - _target_: data.RandomCompress
        method: "JPEG"
        qf: [70, 100]
      - _target_: torchvision.transforms.CenterCrop
        size: 224
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [ 0.48145466, 0.4578275, 0.40821073]
        std: [ 0.26862954, 0.26130258, 0.27577711]