_base_: _base_arrow.yaml
scenario:
  transform:
    trsf:
      - _target_: caidbench.data.transforms.SquareResize
        size: 128
      - _target_: caidbench.data.transforms.ToTensor
      - _target_: caidbench.data.transforms.Normalize
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
method:
  name: cored
  kd_weight: 1.0
  feature_kd_weight: 0.0
  representation_kd_weight: 1.0
  temperature: 20.0
train:
  optimizer:
    type: sgd
    lr: 0.05
    momentum: 0.1
