_base_: _base.yaml
output_dir: outputs/e3_cddb_hard

scenario:
  transform:
    train:
      trsf:
        - _target_: caidbench.data.transforms.ResizeIfSmaller
          size: 256
        - _target_: caidbench.data.transforms.RandomCrop
          size: 256
        - _target_: caidbench.data.transforms.Compress
          method: JPEG
          qf: 99
        - _target_: caidbench.data.transforms.ToTensor
    test:
      trsf:
        - _target_: caidbench.data.transforms.ResizeIfSmaller
          size: 256
        - _target_: caidbench.data.transforms.CenterCrop
          size: 256
        - _target_: caidbench.data.transforms.Compress
          method: JPEG
          qf: 99
        - _target_: caidbench.data.transforms.ToTensor

train:
  epochs: 150
  batch_size: 64
  num_workers: 4
  optimizer:
    type: adamw
    lr: 1.0e-4
    weight_decay: 0.01

method:
  name: e3
  memory_size: 1000
  train_dataset_limit_per_class: 500
  train_dataset_limit_real: 500
  baseline_epochs: 150
  expert_epochs: 150
  ekfn_epochs: 150
  baseline_lr: 1.0e-4
  ft_lr: 5.0e-5
  cls_lr: 2.5e-4
  weight_decay: 0.01
  baseline_lr_step_size: 3
  baseline_lr_gamma: 0.75
  lr_step_size: 100000
  lr_decay_rate: 0.8
  loss_weights: [1.0, 1.0]
  ekfn_layers: 5
  ekfn_heads: 8
  ekfn_train_classifier_head_only: true
  detector_cfg:
    backbone:
      type: mislnet
      patch_size: 256
      num_filters: 6
      constrained_conv: true
