_base_: _base.yaml
output_dir: outputs/e3_cddb_hard
method:
  name: e3
  memory_size: 1000
  memory_batch_size: 32
  replay_group_key: generator
  max_experts: 64
  ekfn_layers: 5
  ekfn_heads: 8
  ekfn_hidden: 64
  ekfn_dropout: 0.5
  ekfn_activation: relu
  detector_cfg:
    backbone:
      out_dim: 200
