_base_: _base.yaml
seed: 1993
output_dir: outputs/ranpac_cddb_hard
scenario:
  protocol: protocols/examples/cddb_hard_official_overall_arrow.yaml
  transform:
    train:
      trsf:
        - _target_: caidbench.data.transforms.Resize
          size: 256
          interpolation: bicubic
        - _target_: caidbench.data.transforms.CenterCrop
          size: 224
        - _target_: caidbench.data.transforms.ToTensor
    test:
      trsf:
        - _target_: caidbench.data.transforms.Resize
          size: 256
          interpolation: bicubic
        - _target_: caidbench.data.transforms.CenterCrop
          size: 224
        - _target_: caidbench.data.transforms.ToTensor
train:
  epochs: 1
  batch_size: 128
  num_workers: 16
method:
  name: ranpac
  num_classes: 2
  detector_cfg:
    num_classes: 2
    backbone:
      type: timm
      name: vit_base_patch16_224_in21k
      pretrained: true
      out_dim: null
  convnet_type: pretrained_vit_b16_224_in21k
  tuned_epoch: 0
  body_lr: 0.0
  head_lr: 0.0
  weight_decay: 0.0005
  min_lr: 0.0
  M: 5000
  use_RP: true
  use_relu: true
  shuffle: true
  use_input_norm: false
  ridge_candidates: [1.0e-8, 1.0e-7, 1.0e-6, 1.0e-5, 1.0e-4, 1.0e-3, 1.0e-2, 1.0e-1, 1.0, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, 10000000.0, 100000000.0]
